version: "3"

services:
  challenge:
    image: mysql:5.7
    networks: 
     - app-network
    volumes: 
     - app_db_volume:/var/lib/mysql
    restart: always
    ports: 
     - "3305:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 5100
      MYSQL_DATABASE: challenge
      MYSQL_USER: root
      MYSQL_PASSWORD: 5100

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
     - "3000:3000"
    tty: true
    volumes:
     - ./server:/app
    networks: 
     - app-network
    environment:
     - NODE_ENV=development
     - DB_HOST=localhost
     - DB_USER=root
     - DB_PASS=5100
     - DB_NAME=challenge
     - DB_DIALECT=mysql
     - DB_PORT=3305
     - APP_HOST=localhost
     - APP_PORT=3000
    command: npm run start
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
     - "8080:8080"
    volumes: 
     - ./client:/app
    environment:
     - NODE_ENV=development
    depends_on: 
     - server
    command: npm run serve

volumes: 
  app_db_volume:

networks: 
  app-network:
